/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 19
#define YY_END_OF_BUFFER 20
static yyconst short int yy_accept[316] =
    {   0,
        0,    0,   20,   19,   19,   16,   19,   13,   16,   16,
       10,   15,   18,   15,   12,   13,   19,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   19,   17,   15,   17,
       10,    0,   14,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   12,    0,    0,    0,    0,    0,
       13,   12,   12,   12,   12,   11,   12,   12,   12,   12,
        0,    0,   14,    0,   10,    0,    0,    7,    7,    0,
        0,    6,    6,    5,    0,    0,    0,    0,    0,    3,
        3,    0,    0,    0,    8,    0,    0,    0,    0,   12,
       11,   12,   12,   11,    0,    0,   12,   12,   12,   12,

       14,    0,    7,    0,    6,    0,    0,    0,    0,    3,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       12,    0,   12,   11,    2,    0,    0,    0,    0,   12,
       12,   12,   12,    7,    6,    0,    0,    3,    0,    0,
        3,    0,    0,    0,    0,    0,    0,    0,   12,    0,
        0,   12,    0,    0,    2,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   12,   12,
       11,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    4,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   12,

        0,    0,    0,    0,    0,    0,    0,    0,    4,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    2,    0,    0,
        0,    0,   12,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   12,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    9,    0,
        0,    0,    0,    0,   12,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,   12,    0,    1,    0,    0,    0,    0,
        0,    0,    0,    0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    3,    1,    1,    5,    6,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,    1,   16,   17,
       18,   19,    1,    1,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       21,    1,   22,    1,    1,    1,   23,   24,   20,   25,

       26,   27,   20,   28,   29,   20,   20,   30,   31,   32,
       33,   20,   34,   35,   36,   37,   38,   20,   39,   20,
       20,   20,   40,   41,   42,   43,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[44] =
    {   0,
        1,    2,    3,    4,    1,    4,    5,    6,    1,    1,
        7,    8,    1,    1,    9,    1,    4,   10,    4,   11,
       12,   13,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,    1,
        4,    1,    4
    } ;

static yyconst short int yy_base[371] =
    {   0,
        0,    0,  742, 1383,  723, 1383,  734, 1383,  724,   35,
       47,  720,  719,  718,   88,   33,  728,  129,   26,  704,
       25,   40,   38,   31,   39,   45,  692, 1383, 1383, 1383,
        0,  723,    0,   63,  713,  724,  714,   69,  710,   86,
      686,   96,   79,   71,  696,   97,  710,  106,   74,   65,
     1383,   80,   93,  108,   92,  123,  109,  112,  120,   17,
      715,  131,    0,  148,  708,  149,  704,  101,    0,  153,
      703,  142,    0, 1383,  702,  163,  169,  170,  701,  166,
        0,  171,  172,  700, 1383,  147,  698,  183,  178,   29,
      203,  172,  171,  682,  201,  204,  185,  124,  187,  680,

      699,  689,    0,  687,    0,  220,  686,  218,  685,    0,
      684,  223,  192,  215,  228,  226,  239,  683,  686,  228,
      195,  252,  293,  250,  244,  247,  681,  334,  375,  665,
      160,  237,  235,  679,  678,  260,  268,  677,  270,  676,
     1383,  255,  675,  279,  267,  301,  287,  284,  258,  682,
      306,  416,  300,  307,  685,  672,  312,  457,  293,  668,
      679,  669,  314,  665,  343,  641,  345,  498,  298,   72,
      332,  351,  354,  356,  663,  666,  322,  353,  352,  668,
      668, 1383,  387,  358,  659,  539,  580,  658,  621,  385,
      328,  393,  657,  372,  663,  398,  655,  376,  661,   95,

      414,  416,  424,  415,  404,  652,  427,  393, 1383,  438,
      278,  440,  462,  648,  439,  662,  399,  643,  654,  644,
      466,  640,  468,  616,  476,  703,  641, 1383,  640,  646,
      638,  644,  432,  394,  636,  744,  785,  461,  417,  482,
      635,  434,  481,  504,  505,  632,  826,  511,  453,  515,
      631,  523,  637,  484,  629,  536,  625,  316,  513,  463,
      605,  551,  867,  509,  601,  590,  580,  522,  558,  557,
      512,  558,  908,  517,  552,  524,  575,  570, 1383,  496,
      495,  497,  475,  481,  518,  457,  949,  590,  564,  591,
      452,  599,  436,  598,  384,  603,  374,  614,  335,  578,

      593,  620,  622,  538,  249, 1383,  237,  205,  126,   85,
      619,  621,  633,  634, 1383,  990,  994, 1006, 1019, 1030,
     1039, 1045, 1054, 1060, 1066, 1069, 1072, 1078, 1081, 1085,
     1091, 1102, 1108, 1113, 1119, 1128, 1137, 1141, 1150, 1155,
     1164, 1170, 1176, 1185, 1194, 1203, 1207, 1213, 1222, 1226,
     1235, 1241, 1247, 1253, 1258, 1269, 1278, 1287, 1296, 1300,
     1309, 1313, 1319, 1325, 1334, 1343, 1352, 1357, 1365, 1371
    } ;

static yyconst short int yy_def[371] =
    {   0,
      315,    1,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  316,  317,  315,  316,   18,   18,
       18,   18,   18,   18,   18,   18,  315,  315,  315,  315,
       11,  318,  319,   11,  315,  315,  315,  320,  315,  320,
      315,  321,   34,  322,   18,  323,  315,  315,  324,  325,
      315,   18,   18,   18,   18,   18,   18,   18,   18,   18,
      318,  318,  319,  320,   34,  320,  315,  315,  326,  321,
      315,  315,  327,  315,  315,  315,  328,  323,  315,  315,
      329,  330,  317,  315,  315,  324,  315,  315,  331,   18,
      332,   18,   18,   18,   43,  333,   18,   18,   18,   18,

      318,  315,  326,  315,  327,  322,  315,  328,  315,  329,
      315,  315,  334,  335,  317,  315,  325,  315,  315,  331,
       18,  336,  337,   18,   18,  338,  315,  315,  339,   18,
       18,   18,   18,  315,  315,  322,  315,  315,  330,  315,
      315,  334,  315,  315,  340,  325,  315,  315,   18,  341,
      342,  337,   43,  343,   43,  315,  128,  344,  157,  315,
      315,  315,  345,  315,  345,  315,  346,  339,   18,   18,
       18,  330,  315,  335,  315,  315,  340,  315,  347,  348,
      341,  315,  349,  350,  315,  315,  351,  315,  344,  345,
      128,  345,  315,  315,  352,  346,  315,  315,  353,   18,

       43,  354,  335,  315,  315,  315,  315,  355,  315,  356,
      348,  349,  349,  315,  186,  357,  215,  315,  315,  315,
      358,  315,  358,  315,  359,  351,  159,  315,  315,  352,
      315,  353,   18,  360,  315,  315,  361,  315,  362,  347,
      315,  315,  355,  356,  356,  315,  357,  358,  186,  358,
      315,  315,  363,  359,  315,  315,  364,  315,  315,   18,
      315,  236,  365,  262,  315,  315,  315,  366,  315,  366,
      315,  367,  361,  315,  315,  368,  347,  315,  315,  217,
      315,  363,  315,  364,   18,  315,  365,  366,  236,  366,
      315,  315,  369,  367,  315,  315,  370,  362,  315,  315,

      368,  315,  315,   18,  264,  315,  315,  369,  315,  370,
      362,  315,  315,  315,    0,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315
    } ;

static yyconst short int yy_nxt[1427] =
    {   0,
        4,    4,    4,    5,    6,    7,    4,    8,    6,    6,
        8,    9,    4,   10,   11,    8,   12,   13,   14,   15,
       16,   17,   15,   18,   19,   20,   21,   15,   22,   15,
       23,   15,   15,   15,   24,   15,   25,   15,   26,    8,
       27,    8,   28,   32,   47,  100,   45,   48,   33,   34,
       35,   53,   36,   50,   45,   45,   58,   55,   45,   37,
       45,   31,  121,   38,   39,   40,   56,   45,   45,   45,
       57,   66,   60,   59,   45,  315,   87,  315,   74,   88,
       67,   43,   75,   68,   83,   76,   64,   41,   66,   42,
       43,   35,  306,   36,   44,   85,   46,   67,   70,   78,

       68,   45,  200,   64,   38,   46,   40,   71,   79,   45,
       72,   80,   90,  102,   64,   68,   83,   82,   84,   91,
       48,   45,   45,  233,   45,   95,   94,   85,   41,   96,
       42,   43,   35,   97,   36,   44,   92,   45,   45,   62,
      314,   45,   99,   93,  101,   38,   46,   40,   98,   45,
       66,   66,   45,   45,  104,   70,   72,   83,   52,   67,
       67,  131,   68,   68,   71,  315,  315,   72,   85,   41,
       74,   42,   78,  106,  115,  107,   74,   76,  109,  106,
       80,   79,  111,   47,   80,  112,   48,  315,  117,   45,
       82,  114,  315,  117,  169,  118,  125,   88,  124,  119,

       45,   45,  139,   95,  119,  122,   35,  126,   36,   44,
      130,   74,  306,  141,   45,  127,   45,   45,  128,   38,
       46,   40,  136,  132,   45,   74,  143,  315,  106,  144,
      115,   75,  149,  139,   76,  140,   83,  112,  117,   47,
      116,  146,   48,   41,  141,   42,  155,   85,  315,  119,
       87,  313,  153,   88,  122,   35,  154,   36,  156,  170,
      171,  157,  136,  305,   45,  139,   45,  315,   38,   46,
       40,   75,  172,   45,   76,   74,  141,  174,  106,   45,
      211,  111,  137,   94,  112,  315,  178,   45,  176,  174,
      315,  175,   41,  144,   42,   43,   35,  117,   36,  151,

      176,  147,  153,  146,  179,  315,  184,  315,  119,   38,
       46,   40,   87,  182,   74,   88,  192,   75,  185,  315,
       76,  186,  315,  228,  188,  193,  157,   45,  194,   94,
      258,  190,  174,   41,  201,   42,  159,  160,  202,  161,
      315,   74,  191,  176,  106,  192,  162,  196,  128,  312,
      163,  164,  165,  172,  193,  178,  197,  194,  203,  198,
      190,   45,  111,  206,  139,  112,  207,  143,  173,  214,
      144,  315,  215,  179,  166,  141,  167,  159,  160,  228,
      161,  306,   74,  228,  229,  106,  194,  192,  231,  211,
      198,  163,  164,  165,  182,  192,  193,  106,  296,  194,

      196,  212,  315,  240,  193,  261,  238,  194,  262,  197,
      315,  315,  198,  315,  242,  166,  201,  167,   43,   35,
      234,   36,  151,   74,  239,  174,  203,  235,  274,  204,
      236,  275,   38,   46,   40,  143,  176,  240,  144,  241,
      211,  207,  211,  306,  148,  209,  315,  182,  242,  315,
      106,  246,  244,  215,  212,  279,   41,  260,   42,  159,
      160,   45,  161,  238,  211,  315,  292,  249,  250,  182,
      250,  305,  106,  163,  164,  165,  212,  251,  254,  251,
      252,  239,  252,  248,  277,  248,  254,  255,  228,  303,
      256,  240,   45,  206,  285,  255,  207,  166,  256,  167,

      159,  160,  242,  161,  228,   74,  211,  211,  106,  302,
      280,  209,  209,  250,  163,  164,  165,  250,  244,  244,
      228,  315,  251,  315,  290,  252,  251,  259,  315,  252,
      228,  275,  315,  291,  298,  281,  292,  252,  166,  288,
      167,  217,  218,  228,  219,  300,   74,   45,  283,  106,
      256,  220,  272,  186,  304,  221,  222,  223,  315,  290,
      294,  315,  298,  286,  299,  262,  275,   45,  291,  295,
       94,  292,  296,  300,  288,  288,  315,  277,  289,  224,
      240,  225,  217,  218,  278,  219,  206,   74,  205,  207,
      106,  242,  290,  290,  289,  272,  221,  222,  223,  141,

      294,  291,  291,  298,  292,  292,  306,  315,  315,  295,
      306,  307,  296,  292,  300,  309,  311,  296,  288,  262,
      224,  311,  225,  159,  160,  274,  161,  228,  275,  228,
      274,  298,  228,  275,  302,  312,  303,  163,  164,  165,
      306,  306,  300,  256,  228,  252,  280,  313,  314,  278,
      236,  228,  259,  228,  258,  227,  225,  248,  249,  225,
      248,  166,  215,  167,  217,  218,  207,  219,  228,  198,
      228,  194,  227,  186,  180,  209,  205,  204,  221,  222,
      223,  167,  190,  191,  167,  190,  157,  155,  180,  144,
      173,  138,  135,  134,   94,  128,  148,  147,  112,  138,

      137,  135,  224,  134,  225,  217,  218,   62,  219,  133,
       74,   45,   88,  106,  116,   80,   76,   72,   68,  221,
      222,  223,   65,   62,   48,   45,   42,   64,   65,   42,
       64,   62,   30,   54,   51,   29,   29,   29,   31,   30,
       29,  315,  315,  224,  315,  225,  264,  265,  315,  266,
      315,   74,  315,  315,  106,  315,  267,  315,  236,  315,
      268,  269,  270,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  271,  315,  272,  264,  265,  315,
      266,  315,   74,  315,  315,  106,  315,  315,  315,  315,

      315,  268,  269,  270,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  271,  315,  272,  217,  218,
      315,  219,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  221,  222,  223,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  224,  315,  225,  264,
      265,  315,  266,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  268,  269,  270,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,

      315,  315,  315,  315,  315,  315,  315,  271,  315,  272,
      264,  265,  315,  266,  315,   74,  315,  315,  106,  315,
      315,  315,  315,  315,  268,  269,  270,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  271,  315,
      272,  264,  265,  315,  266,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  268,  269,  270,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  271,
      315,  272,   45,   45,   45,  315,  315,  315,   45,   45,

       45,   49,   49,  315,   49,   49,   61,  315,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   63,
      315,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   69,  315,  315,  315,  315,   69,   69,   69,
       69,   73,  315,  315,  315,  315,   73,   73,  315,   73,
       77,  315,   77,   77,  315,   77,   81,  315,  315,  315,
      315,   81,   81,   81,   81,   81,   86,  315,   86,  315,
       86,  315,   86,   89,   89,  315,   89,  103,  315,  103,
      105,  315,  105,  108,  108,  315,  108,  315,  108,  110,
      315,  110,  113,  113,  315,  113,  113,  120,  315,  120,

      315,  120,  315,  120,  123,  123,  123,  315,  315,  315,
      123,  123,  123,  129,  315,  129,  129,  315,  129,  142,
      315,  142,  315,  142,  315,  142,  145,  145,  315,  145,
      150,  150,  315,  315,  315,  315,  315,  150,  150,  152,
      152,  152,  315,  315,  315,  152,  152,  152,  158,  158,
      315,  158,  168,  168,  315,  168,  168,  315,  168,  168,
      168,  177,  315,  177,  315,  177,  315,  177,  181,  315,
      315,  315,  181,  315,  181,  183,  315,  183,  183,  315,
      183,  187,  315,  187,  187,  315,  187,  189,  189,  315,
      315,  315,  315,  189,  189,  189,  195,  315,  315,  315,

      315,  195,  195,  195,  195,  199,  315,  315,  315,  315,
      199,  199,  315,  199,  208,  208,  315,  208,  210,  315,
      315,  315,  315,  210,  213,  315,  315,  213,  213,  315,
      213,  315,  213,  216,  216,  315,  216,  226,  226,  315,
      226,  226,  315,  226,  226,  226,  230,  315,  315,  230,
      315,  230,  232,  315,  315,  232,  315,  232,  237,  315,
      237,  237,  315,  237,  243,  315,  243,  315,  243,  315,
      243,  245,  315,  315,  245,  315,  315,  245,  315,  245,
      247,  247,  315,  315,  315,  315,  247,  247,  247,  253,
      315,  315,  315,  315,  253,  253,  253,  253,  257,  315,

      315,  315,  315,  257,  257,  315,  257,  263,  263,  315,
      263,  273,  273,  315,  273,  273,  315,  273,  273,  273,
      276,  276,  315,  276,  282,  315,  315,  282,  315,  282,
      284,  315,  315,  284,  315,  284,  287,  287,  315,  315,
      315,  315,  287,  287,  287,  293,  315,  315,  315,  315,
      293,  293,  293,  293,  297,  315,  315,  315,  315,  297,
      297,  315,  297,  301,  315,  301,  315,  301,  315,  301,
      308,  315,  315,  308,  315,  308,  310,  315,  315,  310,
      315,  310,    3,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,

      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315
    } ;

static yyconst short int yy_chk[1427] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   10,   16,   60,   60,   16,   10,   11,
       11,   19,   11,   16,   21,   19,   24,   21,   90,   11,
       24,   11,   90,   11,   11,   11,   22,   23,   25,   22,
       23,   38,   26,   25,   26,   34,   50,   34,   44,   50,
       38,   43,   44,   38,   49,   44,   38,   11,   40,   11,
       15,   15,  310,   15,   15,   49,   43,   40,   42,   46,

       40,  170,  170,   40,   15,   15,   15,   42,   46,   52,
       42,   46,   52,   68,   46,   68,   48,   46,   48,   53,
       48,   55,   53,  200,  200,   56,   55,   48,   15,   56,
       15,   18,   18,   57,   18,   18,   54,   54,   57,   62,
      309,   58,   59,   54,   62,   18,   18,   18,   58,   59,
       64,   66,   56,   98,   72,   70,   72,   86,   18,   64,
       66,   98,   64,   66,   70,   64,   66,   70,   86,   18,
       76,   18,   78,   76,   83,   76,   77,   76,   80,   77,
       80,   78,   82,   83,   78,   82,   83,   78,   89,  131,
       78,   82,   83,   88,  131,   88,   93,   88,   92,   89,

       93,   92,  113,   95,   88,   91,   91,   95,   91,   91,
       97,   96,  308,  113,   97,   96,   99,   91,   96,   91,
       91,   91,  106,   99,  121,  108,  114,  106,  108,  114,
      115,  106,  121,  112,  106,  112,  116,  112,  120,  115,
      116,  117,  115,   91,  112,   91,  125,  116,  115,  120,
      117,  307,  124,  117,  122,  122,  124,  122,  126,  132,
      133,  126,  136,  305,  133,  142,  132,  136,  122,  122,
      122,  136,  139,  125,  136,  137,  142,  145,  137,  124,
      211,  139,  137,  149,  139,  211,  148,  149,  145,  144,
      139,  144,  122,  144,  122,  123,  123,  147,  123,  123,

      144,  147,  153,  146,  148,  159,  153,  159,  147,  123,
      123,  123,  146,  151,  154,  146,  163,  151,  154,  157,
      151,  154,  157,  258,  157,  163,  157,  169,  163,  169,
      258,  163,  177,  123,  171,  123,  128,  128,  171,  128,
      191,  128,  191,  177,  128,  165,  128,  167,  128,  299,
      128,  128,  128,  172,  165,  178,  167,  165,  174,  167,
      165,  171,  172,  179,  173,  172,  179,  174,  173,  184,
      174,  172,  184,  178,  128,  173,  128,  129,  129,  194,
      129,  297,  129,  198,  194,  129,  194,  190,  198,  183,
      198,  129,  129,  129,  183,  192,  190,  183,  295,  190,

      196,  183,  190,  208,  192,  234,  205,  192,  234,  196,
      192,  217,  196,  217,  208,  129,  201,  129,  152,  152,
      201,  152,  152,  202,  205,  204,  203,  202,  239,  204,
      202,  239,  152,  152,  152,  203,  204,  207,  203,  207,
      210,  207,  212,  293,  242,  210,  215,  212,  207,  215,
      212,  215,  210,  215,  212,  242,  152,  233,  152,  158,
      158,  233,  158,  238,  213,  249,  291,  249,  221,  213,
      223,  286,  213,  158,  158,  158,  213,  221,  225,  223,
      221,  238,  223,  221,  240,  223,  254,  225,  284,  283,
      225,  243,  260,  240,  260,  254,  240,  158,  254,  158,

      168,  168,  243,  168,  282,  168,  244,  245,  168,  281,
      280,  244,  245,  248,  168,  168,  168,  250,  244,  245,
      259,  264,  248,  264,  268,  248,  250,  259,  248,  250,
      252,  274,  250,  268,  276,  252,  268,  252,  168,  268,
      168,  186,  186,  256,  186,  276,  186,  285,  256,  186,
      256,  186,  271,  186,  285,  186,  186,  186,  262,  270,
      272,  262,  275,  262,  275,  262,  275,  304,  270,  272,
      304,  270,  272,  275,  270,  269,  289,  277,  289,  186,
      278,  186,  187,  187,  278,  187,  277,  187,  300,  277,
      187,  278,  288,  290,  267,  266,  187,  187,  187,  300,

      294,  288,  290,  301,  288,  290,  292,  288,  290,  294,
      296,  292,  294,  292,  301,  296,  298,  296,  265,  261,
      187,  311,  187,  189,  189,  298,  189,  302,  298,  303,
      311,  312,  257,  311,  302,  312,  303,  189,  189,  189,
      313,  314,  312,  255,  253,  251,  246,  313,  314,  241,
      235,  232,  231,  230,  229,  227,  224,  222,  220,  219,
      218,  189,  214,  189,  216,  216,  206,  216,  199,  197,
      195,  193,  188,  185,  181,  180,  176,  175,  216,  216,
      216,  166,  164,  162,  161,  160,  156,  155,  150,  143,
      140,  138,  135,  134,  130,  127,  119,  118,  111,  109,

      107,  104,  216,  102,  216,  226,  226,  101,  226,  100,
      226,   94,   87,  226,   84,   79,   75,   71,   67,  226,
      226,  226,   65,   61,   47,   45,   41,   39,   37,   36,
       35,   32,   27,   20,   17,   14,   13,   12,    9,    7,
        5,    3,    0,  226,    0,  226,  236,  236,    0,  236,
        0,  236,    0,    0,  236,    0,  236,    0,  236,    0,
      236,  236,  236,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  236,    0,  236,  237,  237,    0,
      237,    0,  237,    0,    0,  237,    0,    0,    0,    0,

        0,  237,  237,  237,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  237,    0,  237,  247,  247,
        0,  247,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  247,  247,  247,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  247,    0,  247,  263,
      263,    0,  263,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  263,  263,  263,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,  263,    0,  263,
      273,  273,    0,  273,    0,  273,    0,    0,  273,    0,
        0,    0,    0,    0,  273,  273,  273,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  273,    0,
      273,  287,  287,    0,  287,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  287,  287,  287,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  287,
        0,  287,  316,  316,  316,    0,    0,    0,  316,  316,

      316,  317,  317,    0,  317,  317,  318,    0,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  319,
        0,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  320,    0,    0,    0,    0,  320,  320,  320,
      320,  321,    0,    0,    0,    0,  321,  321,    0,  321,
      322,    0,  322,  322,    0,  322,  323,    0,    0,    0,
        0,  323,  323,  323,  323,  323,  324,    0,  324,    0,
      324,    0,  324,  325,  325,    0,  325,  326,    0,  326,
      327,    0,  327,  328,  328,    0,  328,    0,  328,  329,
        0,  329,  330,  330,    0,  330,  330,  331,    0,  331,

        0,  331,    0,  331,  332,  332,  332,    0,    0,    0,
      332,  332,  332,  333,    0,  333,  333,    0,  333,  334,
        0,  334,    0,  334,    0,  334,  335,  335,    0,  335,
      336,  336,    0,    0,    0,    0,    0,  336,  336,  337,
      337,  337,    0,    0,    0,  337,  337,  337,  338,  338,
        0,  338,  339,  339,    0,  339,  339,    0,  339,  339,
      339,  340,    0,  340,    0,  340,    0,  340,  341,    0,
        0,    0,  341,    0,  341,  342,    0,  342,  342,    0,
      342,  343,    0,  343,  343,    0,  343,  344,  344,    0,
        0,    0,    0,  344,  344,  344,  345,    0,    0,    0,

        0,  345,  345,  345,  345,  346,    0,    0,    0,    0,
      346,  346,    0,  346,  347,  347,    0,  347,  348,    0,
        0,    0,    0,  348,  349,    0,    0,  349,  349,    0,
      349,    0,  349,  350,  350,    0,  350,  351,  351,    0,
      351,  351,    0,  351,  351,  351,  352,    0,    0,  352,
        0,  352,  353,    0,    0,  353,    0,  353,  354,    0,
      354,  354,    0,  354,  355,    0,  355,    0,  355,    0,
      355,  356,    0,    0,  356,    0,    0,  356,    0,  356,
      357,  357,    0,    0,    0,    0,  357,  357,  357,  358,
        0,    0,    0,    0,  358,  358,  358,  358,  359,    0,

        0,    0,    0,  359,  359,    0,  359,  360,  360,    0,
      360,  361,  361,    0,  361,  361,    0,  361,  361,  361,
      362,  362,    0,  362,  363,    0,    0,  363,    0,  363,
      364,    0,    0,  364,    0,  364,  365,  365,    0,    0,
        0,    0,  365,  365,  365,  366,    0,    0,    0,    0,
      366,  366,  366,  366,  367,    0,    0,    0,    0,  367,
      367,    0,  367,  368,    0,  368,    0,  368,    0,  368,
      369,    0,    0,  369,    0,  369,  370,    0,    0,  370,
        0,  370,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,

      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "taller1.l"
#define INITIAL 0
#line 2 "taller1.l"

#undef yywrap
#define yywrap() 1 
#include <stdio.h>
#include <string.h>

void imprimir(char *valor, char *categoria);

#line 800 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 37 "taller1.l"


#line 954 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 316 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1383 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 39 "taller1.l"
{
    imprimir(yytext,"ITERACION");
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 43 "taller1.l"
{
    imprimir(yytext,"SELECCION");
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 47 "taller1.l"
{
    imprimir(yytext,"ASIGNACION");
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 51 "taller1.l"
{
    imprimir(yytext,"FUNCION");
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 55 "taller1.l"
{
    imprimir(yytext,"LLAMADA_FUNCION");
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 59 "taller1.l"
{
    imprimir(yytext,"OPERACION_LOGICA");
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 63 "taller1.l"
{
    imprimir(yytext,"OPERACION_COMPARACION");
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 68 "taller1.l"
{
    imprimir(yytext,"ARREGLO");
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 72 "taller1.l"
{
    imprimir(yytext,"MATRIZ");
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 76 "taller1.l"
{
    imprimir(yytext,"NUMERO");
} 
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 80 "taller1.l"
{
    imprimir(yytext,"PALABRAS_RESERVADAS");
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 84 "taller1.l"
{
    imprimir(yytext,"VARIABLE");
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 88 "taller1.l"
{
    imprimir(yytext,"DELIMITADOR");
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 92 "taller1.l"
{
    imprimir(yytext,"COMENTARIO");
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 97 "taller1.l"
{
    imprimir(yytext,"OPERADOR_COMPARACION");
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 101 "taller1.l"
{
    imprimir(yytext,"OPERADOR_ARITMETICO");
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 105 "taller1.l"
{
    imprimir(yytext,"OPERADOR_LOGICO");
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 109 "taller1.l"
{
    imprimir(yytext,"OPERADOR_ASIGNACION");
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 113 "taller1.l"
ECHO;
	YY_BREAK
#line 1168 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 316 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 316 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 315);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 113 "taller1.l"

 
int main()
{
  yyin = fopen("texto.txt","r");
  yylex();
  return 0;
}

void imprimir(char *valor, char *categoria)
{
    if(strcmp(valor, ";") == 1)
    {
        printf("\n");
    }
    printf( "( %s , %s ) ", valor, categoria );
}